services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    environment:
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
    depends_on:
      - db
  db:
    image: 'mariadb:latest'
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE="ecommerce"
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
    ports:
      - '3306'

volumes:
  db_data:
