services:
    app:
        build:
            context: ../
            dockerfile: Dockerfile
        env_file:
            - ../.env
        image: firo1919/ecommerce-backend
        networks:
            - app
        volumes:
            - app_images:/store/images
        ports:
            - "8080:8080"
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped
    db:
        env_file:
            - ../.env.db
        image: "mariadb:latest"
        restart: unless-stopped
        volumes:
            - db_data_prod:/var/lib/mysql
        networks:
            - app
        healthcheck:
            test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s

volumes:
    db_data_prod:
    app_images:

networks:
    app:
