name: Deploy Backend Dev

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: ./Backend
                  file: ./Backend/docker/Dockerfile
                  push: true
                  tags: firo1919/ecommerce-backend:dev
                  platforms: linux/amd64,linux/arm64
                  cache-from: type=registry,ref=firo1919/ecommerce-backend:dev
                  cache-to: type=registry,ref=firo1919/ecommerce-backend:dev,mode=max
    render:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to dev
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                  service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
                  api-key: ${{ secrets.MY_RENDER_API_KEY }}
                  wait-for-success: true
