name: Test Backend

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: Backend
        container:
            image: maven:3.9.9-eclipse-temurin-21
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Cache Maven packages
              uses: actions/cache@v3
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-

            - name: Test
              run: mvn test -B
